name: FormeraIOS
options:
  bundleIdPrefix: com.formera
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "TT4TYJV7FD"
    CODE_SIGN_STYLE: Automatic
    MARKETING_VERSION: "1.0.1"
    CURRENT_PROJECT_VERSION: "3"

targets:
  FormeraIOS:
    type: application
    platform: iOS
    sources:
      - path: FormeraIOS/Sources
      - path: FormeraIOS/Resources
    info:
      path: FormeraIOS/Resources/Info.plist
      properties:
        UILaunchScreen: {}
        CFBundleDisplayName: Formera
        UIRequiresFullScreen: true
        ITSAppUsesNonExemptEncryption: false
        APIBaseURL: $(API_BASE_URL)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        NSAppTransportSecurity:
          NSExceptionDomains:
            localhost:
              NSExceptionAllowsInsecureHTTPLoads: true
            192.168.0.190:
              NSExceptionAllowsInsecureHTTPLoads: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.formera.ios
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      configs:
        Debug:
          API_BASE_URL: "http://192.168.0.190:8000/api/"
        Release:
          API_BASE_URL: "https://formera-api-833262393415.us-west2.run.app/api/"

schemes:
  FormeraIOS:
    build:
      targets:
        FormeraIOS: all
    run:
      config: Debug
    test:
      config: Debug
    archive:
      config: Release
  FormeraIOS (Release):
    build:
      targets:
        FormeraIOS: all
    run:
      config: Release
    test:
      config: Release
    archive:
      config: Release
